Pandas: Tablas Inteligentes

In [3]:
import pandas as pd
import numpy as np

In [14]:
# Crear desde diccionario: clave=nombre columna, valor=lista de datos
df = pd.DataFrame({
    'producto' : ['Lapto','Mouse', 'Teclado','Monitor'],
    'precio': [2500000,45000,120000,800000],
    'stock':    [15,200,85,30],
    'categoria':['PC','PC','PC','PC']
})

print(df)
print("\nForma:", df.shape)# (4, 4) → 4 filas, 4 columnas
print("Tipos:\n", df.dtypes)

  producto   precio  stock categoria
0    Lapto  2500000     15        PC
1    Mouse    45000    200        PC
2  Teclado   120000     85        PC
3  Monitor   800000     30        PC

Forma: (4, 4)
Tipos:
 producto     object
precio        int64
stock         int64
categoria    object
dtype: object

Exploración — Los 5 Comandos Siempre

In [6]:
df.head()           # primeros 5 registros
df.tail(3)          # últimos 3
df.info()            # tipos de dato, nulos, memoria
df.describe()        # estadísticas de columnas numéricas
df.isnull().sum()   # cuántos nulos por columna

# Frecuencia de cada categoría
df['categoria'].value_counts()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Producto   4 non-null      object
 1   Precio     4 non-null      int64
 2   stock      4 non-null      int64
 3   categoria  4 non-null      object
dtypes: int64(2), object(2)
memory usage: 260.0+ bytes

categoria
PC    4
Name: count, dtype: int64

Seleccionar y Filtrar

In [7]:
# Una columna → Series
precios = df['precio']

# Varias columnas → DataFrame
sub = df[['producto' , 'precio']]

# Filtrar filas con condición booleana
caros = df[df['precio'] > 200000]

# Múltiples condiciones
filtro = df[(df['precio'] > 100000) & (df['stock'] > 20)]

# Por posición: iloc[filas, columnas]
# Por posición: iloc[filas, columnas]
df.iloc[0]            # primera fila
df.iloc[1:3]          # filas 1 y 2
df.iloc[:, 1:3]       # todas las filas, columnas 1 y 2

# Por etiqueta: loc
df.loc[df['precio'] == df['precio'].max()]  # fila del más caro

KeyError: 'precio'

Limpieza de Datos

In [9]:
df2 = pd.DataFrame({
    'nombre': ['Ana','Luis','Ana', None,'Marta'],
    'edad':   [25,30,25,28,None],
    'ventas': [1000,2000,1000,1500,1200]
})

# Ver nulos por columna
print(df2.isnull().sum())
# nombre 1  edad 1  ventas 0

# Estrategia 1: eliminar filas con nulos
df_clean = df2.dropna()

# Estrategia 2: rellenar nulos
df2['edad'] = df2['edad'].fillna(df2['edad'].mean())
df2['nombre'] = df2['nombre'].fillna('sin nombre')

# Eliminar duplicados
df2 = df2.drop_duplicates()

# Crear nueva columna
df2['ventas_usd'] = (df2['ventas'] / 4200).round(2)

# Columna condicional
df2['rendimiento'] = np.where(df2['ventas'] >= 1500, 'Alto', 'Bajo')

nombre    1
edad      1
ventas    0
dtype: int64

GroupBy — Agrupar y Resumir

In [15]:
# Promedio de ventas por departamento
df.groupby('categoria')['precio'].mean()

# Múltiples estadísticas a la vez
df.groupby('categoria').agg({
    'precio': ['mean','max','min'],
    'stock':  ['sum','count']
})

# Ordenar resultado
df.sort_values('precio', ascending=False)

  producto   precio  stock categoria
0    Lapto  2500000     15        PC
3  Monitor   800000     30        PC
2  Teclado   120000     85        PC
1    Mouse    45000    200        PC

Ejercicios del Capítulo

Análisis de Empleados
Crea este DataFrame: {'nombre':['Carlos','María','Juan','Ana','Pedro','Laura'], 'departamento':['Ventas','IT','Ventas','IT','RRHH','Ventas'], 'salario':[3200000,5500000,2800000,6000000,3500000,3800000], 'años':[3,7,1,10,5,4]}

¿Cuántos empleados por departamento?
Salario promedio por departamento.
Solo empleados de IT.
¿Quién gana más de 4M Y lleva más de 3 años?

In [18]:
df3 = pd.DataFrame({'nombre':['Carlos','María','Juan','Ana','Pedro','Laura'],
                    'departamento':['Ventas','IT','Ventas','IT','RRHH','Ventas'],
                    'salario':[3200000,5500000,2800000,6000000,3500000,3800000],
                    'años':[3,7,1,10,5,4]})

print(df3)

   nombre departamento  salario  años
0  Carlos       Ventas  3200000     3
1   María           IT  5500000     7
2    Juan       Ventas  2800000     1
3     Ana           IT  6000000    10
4   Pedro         RRHH  3500000     5
5   Laura       Ventas  3800000     4

In [19]:
# 1. Empleados por departamento
print(df3['departamento'].value_counts())
# Ventas 3  IT 2  RRHH 1

departamento
Ventas    3
IT        2
RRHH      1
Name: count, dtype: int64

In [20]:
# 2. Salario promedio por departamento
print(df3.groupby('departamento')['salario'].mean())
# IT 5750000  RRHH 3500000  Ventas 3266667

departamento
IT        5.750000e+06
RRHH      3.500000e+06
Ventas    3.266667e+06
Name: salario, dtype: float64

In [22]:
# 3. Solo IT
print(df3[df3['departamento'] == 'IT'])

  nombre departamento  salario  años
1  María           IT  5500000     7
3    Ana           IT  6000000    10

In [26]:
# 4. Salario > 4M Y más de 3 años
resultado = df3[(df3['salario'] > 4000000) & (df3['años']> 3)]
print(resultado)
print(resultado[['nombre','salario','años']])

  nombre departamento  salario  años
1  María           IT  5500000     7
3    Ana           IT  6000000    10
  nombre  salario  años
1  María  5500000     7
3    Ana  6000000    10

Limpieza Real de Datos
Dataset sucio: {'cliente':['Juan','Ana','Juan',None,'Pedro'], 'compra':[15000,None,15000,8000,22000], 'ciudad':['Cali','Bogotá','Cali','Medellín','Cali']}

Identifica nulos por columna.
Rellena 'compra' nulo con el promedio de las compras conocidas.
Rellena 'cliente' nulo con 'Sin identificar'.
Elimina duplicados.
Crea columna 'compra_usd' dividiendo entre 4200.

In [27]:
df = pd.DataFrame({
    'cliente':['Juan','Ana','Juan',None,'Pedro'],
    'compra': [15000,None,15000,8000,22000],
    'ciudad': ['Cali','Bogotá','Cali','Medellín','Cali']
})

print("Nulos:\n", df.isnull().sum())
# cliente 1  compra 1  ciudad 0

df['compra']  = df['compra'].fillna(df['compra'].mean())  # 15000.0
df['cliente'] = df['cliente'].fillna('Sin identificar')

df = df.drop_duplicates()
print("Filas limpias:", len(df))  # 4

df['compra_usd'] = (df['compra'] / 4200).round(2)
print(df)

Nulos:
 cliente    1
compra     1
ciudad     0
dtype: int64
Filas limpias: 4
           cliente   compra    ciudad  compra_usd
0             Juan  15000.0      Cali        3.57
1              Ana  15000.0    Bogotá        3.57
3  Sin identificar   8000.0  Medellín        1.90
4            Pedro  22000.0      Cali        5.24